[package]
name = "lagato"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
cgmath = { version = "0.16", features = ["serde"] }
serde = "1"
serde_derive = "1"
