[package]
name = "lagato"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
alga = "0.5"
nalgebra = { version = "0.14", features = ["serde-serialize"] }
serde = "1"
serde_derive = "1"
