[package]
name = "rivr"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
metrohash = "1"
nalgebra = "0.14"
palette = "0.3"
cassowary = "0.3"
lyon = "0.10"
rusttype = "0.5"
